# Generated by Django 4.0.2 on 2024-07-02 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websites',
            name='dateOfDevelopment',
        ),
        migrations.AddField(
            model_name='websites',
            name='date_of_development',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
