# Generated by Django 4.0.2 on 2024-07-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_remove_websites_dateofdevelopment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websites',
            name='date_of_development',
        ),
        migrations.AddField(
            model_name='websites',
            name='year_of_development',
            field=models.IntegerField(default=2000),
        ),
    ]
