# Generated by Django 4.0.2 on 2024-07-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_remove_websites_date_of_development_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research_Scholars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('research_topic', models.CharField(max_length=250)),
                ('enrollment_date', models.DateTimeField()),
                ('date_of_completion', models.CharField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', max_length=10)),
                ('phone', models.CharField(default='0000000000', max_length=10)),
                ('email', models.CharField(default='abc123@gmail.com', max_length=60)),
                ('address', models.CharField(default=' ', help_text='Format :: Locality:/District:/State:/Country:/PIN:', max_length=100)),
                ('net_JRF', models.BooleanField(default=False)),
                ('image', models.ImageField(default='static/profiles/rscholars/default.png', upload_to='static/profiles/rscholars/')),
            ],
            options={
                'verbose_name_plural': 'Research Scholars',
            },
        ),
    ]
