# Generated by Django 4.0.2 on 2024-07-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_research_scholars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_scholars',
            name='enrollment_date',
            field=models.DateField(),
        ),
    ]
