# Generated by Django 4.0.2 on 2024-07-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_invited_lectures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sponsored_by', models.CharField(max_length=100)),
                ('start_date', models.CharField(help_text='Format : DD[th]_Month,_YYYY  ; Example : 20th March, 2018', max_length=30)),
                ('end_date', models.CharField(blank=True, help_text='Format : DD[th]_Month,_YYYY  ; Example : 19th March, 2019', max_length=30, null=True)),
                ('duration', models.CharField(max_length=10)),
                ('amount', models.CharField(help_text='Amount allocated for the completion of Project', max_length=16)),
                ('other_persons', models.CharField(help_text='Use a comma separated list : name1, name2, name3...', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
