# Generated by Django 4.0.2 on 2024-07-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_remove_projects_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='end_date',
            field=models.CharField(blank=True, help_text='Format : DD[th]_Month,_YYYY  ; Example : 19th March, 2019', max_length=30, null=True),
        ),
    ]
