# Generated by Django 4.0.2 on 2024-07-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_awards_award_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_presentation', models.CharField(max_length=200)),
                ('file_name', models.FileField(blank=True, null=True, upload_to='static/files/presentation')),
            ],
            options={
                'verbose_name_plural': "PPT's",
            },
        ),
        migrations.AlterField(
            model_name='awards',
            name='awarding_agency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='awards',
            name='conferred_on',
            field=models.CharField(help_text='Please use the following format: DD MONTH-NAME, YYYY. Eg:21 March, 2019', max_length=20),
        ),
        migrations.AlterField(
            model_name='awards',
            name='image',
            field=models.ImageField(blank=True, default='static/gallary/awards/default.jpg', help_text='Default is /static/gallary/awards/default.jpg', upload_to='static/gallary/awards/'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='name_of_the_award',
            field=models.CharField(max_length=150),
        ),
    ]
