# Generated by Django 4.0.2 on 2024-07-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_presentation_alter_awards_awarding_agency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles_In_Journals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_article', models.CharField(max_length=200)),
                ('journal_name', models.CharField(help_text='Name of the Journal in which article was featured. Along with indexing information.', max_length=200)),
                ('along_with', models.CharField(blank=True, help_text='Maximum 20 characters allowed, Try to complete the name within the limit.', max_length=20, null=True)),
                ('year', models.CharField(default='NA', help_text='Please provide the Year only <em>YYYY</em>. Eg: 2012', max_length=5)),
                ('link', models.CharField(blank=True, help_text='Please input the file name correctly with correct extension', max_length=250, null=True)),
                ('file_name', models.FileField(blank=True, null=True, upload_to='static/files/articles')),
                ('file_name_uploaded', models.BooleanField(blank=True, help_text='If you have uploaded the file Select True else Select False.', null=True)),
            ],
            options={
                'verbose_name_plural': 'Articles In Journals',
            },
        ),
    ]
