# Generated by Django 4.0.2 on 2024-07-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_articles_in_journals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters_In_Edited_Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=150)),
                ('book_name', models.CharField(help_text='Name of the book where the chapter is published.', max_length=200)),
                ('editors', models.CharField(default='NA', help_text='Provide a comma separated list. Note: Use NA if publisher is not available. Minimum Charater 5 for Editors Name', max_length=60)),
                ('published_by', models.CharField(default='NA', help_text='Note: Use NA if publisher is not available. Minimum Charater 5 for Publisher Name.', max_length=100)),
                ('year', models.CharField(default='NA', help_text='Please provide the Year only YYYY', max_length=5)),
                ('pages', models.CharField(default='NA', help_text='Use format Start_page_num - Ending_page_no. Eg : 201-214', max_length=14)),
                ('link', models.CharField(blank=True, help_text='Please input the file name correctly with correct extension', max_length=250, null=True)),
                ('link_available', models.BooleanField(default=False, help_text='If you have provided the link Select the box else leave it blank.')),
            ],
            options={
                'verbose_name_plural': 'Chapters In Edited Books',
            },
        ),
        migrations.AlterField(
            model_name='articles_in_journals',
            name='file_name_uploaded',
            field=models.BooleanField(default=False, help_text='If you have uploaded the file click the box else leave it unchecked.'),
        ),
        migrations.AlterField(
            model_name='articles_in_journals',
            name='title_of_article',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='articles_in_journals',
            name='year',
            field=models.CharField(default=2024, help_text='Please provide the Year only <em>YYYY</em>. Eg: 2012', max_length=5),
        ),
    ]
