# Generated by Django 4.0.2 on 2024-07-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0014_chapters_in_edited_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters_in_edited_books',
            name='along_with',
            field=models.CharField(blank=True, help_text='Maximum 20 characters allowed, Try to complete the name within the limit.', max_length=20, null=True),
        ),
    ]
