# Generated by Django 4.0.2 on 2024-07-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0015_chapters_in_edited_books_along_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150)),
                ('sub_title', models.TextField(default='NA', help_text='Maximum Length is 300 characters.Minimum is 5 characters.', max_length=300)),
                ('author_editor_compiler', models.CharField(default='NA', help_text='In case of multiple authors use a comma separated list.', max_length=100)),
                ('contributors', models.CharField(default='NA', help_text='Maximum 100 charaters allowd in this field.', max_length=100)),
                ('about_the_book', models.TextField(default='NA', help_text='Minimum text 20 characters is needed about the book. Maximum 2000 characters.', max_length=2000)),
                ('publisher', models.CharField(default='NA', help_text='Maximum 60 characters allowed in this field.', max_length=60)),
                ('binding', models.CharField(default='PaperBack', max_length=40)),
                ('language', models.CharField(default='English', max_length=60)),
                ('genre', models.CharField(default='Language Arts', max_length=80)),
                ('place', models.CharField(default='Assam', help_text='Maximum 60 charaters allowed in this field.', max_length=60)),
                ('year', models.CharField(default='2000', help_text='Please provide the Year only <em>YYYY</em>', max_length=4)),
                ('pages', models.IntegerField(default=0, help_text='Total no of pages here.')),
                ('dimensions', models.CharField(default='NA', help_text='format = Height X Width X Depth. Eg: 28cm X 8cm X 2cm', max_length=20)),
                ('original_price', models.IntegerField(default=0, help_text='The Price written on the Book')),
                ('sale_price', models.IntegerField(default=0, help_text='The Price for which the Book is to be sold')),
                ('isbn_issn', models.CharField(default='NA', max_length=60)),
                ('show_total_no_of_units_sold', models.BooleanField(default=False)),
                ('total_no_of_units_sold', models.CharField(help_text='Eg: 1 million +', max_length=50)),
                ('availability', models.CharField(choices=[('proceed', 'BUY'), ('link', 'Link'), ('unavailable', 'Unavailable'), ('no_stock', 'Out of Stock')], default='Unavailable', help_text='If Link selected then provide the link below.', max_length=20)),
                ('is_book_link_available', models.BooleanField(default=False)),
                ('book_link_to_other_sources', models.CharField(default='NA', max_length=200)),
                ('image', models.ImageField(blank=True, default='static/gallary/books/default.jpg', upload_to='static/gallary/books/')),
                ('book_cover_color', models.CharField(choices=[('rose', 'Rose'), ('pink', 'Pink'), ('fuchsia', 'Purple'), ('violet', 'Violet'), ('indigo', 'Indigo'), ('blue', 'Blue'), ('cyan', 'Light Blue'), ('teal', 'Violet'), ('emerald', 'Dark Green'), ('green', 'Light Green'), ('lime', 'Parrot'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red'), ('stone', 'Brown'), ('gray', 'Gray')], default='Gray', help_text='This color is use to match the background in HTML Document with that of the book.', max_length=15)),
                ('priority', models.IntegerField(help_text='This Number is used to denote the priority of the book. Higher the No. higher is the positon of the book in the HTML.', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
    ]
