# Generated by Django 4.0.2 on 2024-07-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0016_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='weight',
            field=models.CharField(blank=True, default='NA', help_text='format = Value Kg. Eg: 2.1 Kg.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='author_editor_compiler',
            field=models.CharField(default='Dr. Badan Barman', help_text='In case of multiple authors use a comma separated list.', max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_cover_color',
            field=models.CharField(choices=[('rose', 'Rose'), ('pink', 'Pink'), ('fuchsia', 'Purple'), ('violet', 'Violet'), ('indigo', 'Indigo'), ('blue', 'Blue'), ('cyan', 'Light Blue'), ('teal', 'Teal'), ('emerald', 'Dark Green'), ('green', 'Light Green'), ('lime', 'Parrot'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red'), ('stone', 'Brown'), ('gray', 'Gray')], default='Gray', help_text='This color is use to match the background in HTML Document with that of the book.', max_length=15),
        ),
        migrations.AlterField(
            model_name='books',
            name='contributors',
            field=models.CharField(default='Dr. Badan Barman', help_text='Maximum 100 charaters allowd in this field.', max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='place',
            field=models.CharField(default='Guwahati, Assam', help_text='Maximum 60 charaters allowed in this field.', max_length=60),
        ),
        migrations.AlterField(
            model_name='books',
            name='total_no_of_units_sold',
            field=models.CharField(default='NA', help_text='Eg: 1 million +', max_length=50),
        ),
    ]
