# Generated by Django 4.0.2 on 2024-07-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0017_books_weight_alter_books_author_editor_compiler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author_editor_compiler', models.TextField(default='NA', max_length=300)),
                ('publisher', models.CharField(default='NA', max_length=60)),
                ('place', models.CharField(default='NA', max_length=60)),
                ('volume', models.CharField(default='NA', max_length=15)),
                ('issue', models.CharField(default='NA', max_length=20)),
                ('month', models.CharField(default='NA', help_text='Provide the First 3 letter of the Month only if possible. Eg: Jan-Feb or Apr', max_length=20)),
                ('year', models.CharField(default='NA', help_text='Please provide the Year only <em>YYYY</em>', max_length=5)),
                ('pages', models.CharField(default='NA', max_length=10)),
                ('price', models.IntegerField(default=0, help_text='The Price of the Periodical.')),
                ('isbn_issn', models.CharField(max_length=50)),
                ('is_purchase_possible', models.BooleanField(default=False, help_text='Is the book available to purchase. If YES ,tick the checkbox.')),
                ('link', models.CharField(default='NA', help_text='Provide the link to Purchase or Download the edition.', max_length=200)),
                ('image', models.ImageField(blank=True, default='static/gallary/periodicals/default.jpg', upload_to='static/gallary/periodicals/')),
            ],
            options={
                'verbose_name_plural': 'Periodicals',
            },
        ),
    ]
