# Generated by Django 4.0.2 on 2024-07-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0018_periodicals'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicals',
            name='about_the_book',
            field=models.TextField(blank=True, default='NA', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='periodicals',
            name='isbn_issn',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='periodicals',
            name='month',
            field=models.CharField(default='Jan', help_text='Provide the First 3 letter of the Month only if possible. Eg: Jan-Feb or Apr', max_length=20),
        ),
        migrations.AlterField(
            model_name='periodicals',
            name='place',
            field=models.CharField(default='Guwahati', max_length=60),
        ),
        migrations.AlterField(
            model_name='periodicals',
            name='year',
            field=models.CharField(default='2000', help_text='Please provide the Year only <em>YYYY</em>', max_length=5),
        ),
    ]
