# Generated by Django 4.0.2 on 2024-07-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0019_periodicals_about_the_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicals',
            name='about_the_book',
            field=models.TextField(default='NA', max_length=1000),
        ),
    ]
